### ISSUE TITLE
Suddenly alot of lock exceptions is heading my way

### ISSUE THREAD

**Issue by KennethJakobsen** [rebus-org/Rebus.AzureServiceBus#12]
Suddenly i'm experiencing a lot of lock exceptions like this.
Do you know why this is?
```
Rebus.Workers.ThreadPoolBased.ThreadPoolWorker ERROR (Thread #16): An error occurred when attempting to complete the transaction context
Rebus.Exceptions.RebusApplicationException: The message lock for message with ID 1e9682b3-e6ab-4c69-b702-88da2d957de4 was lost - tried to complete after 4,0 s ---> Microsoft.ServiceBus.Messaging.MessageLockLostException: The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue. TrackingId:43249aa7-e8c5-4c3d-ac91-0007c7d98ca6_G24_B2, SystemTracker:umbksjdev:Queue:letsencrypt-input, Timestamp:4/30/2018 2:13:30 PM ---> System.ServiceModel.FaultException`1[System.ServiceModel.ExceptionDetail]: The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue. TrackingId:43249aa7-e8c5-4c3d-ac91-0007c7d98ca6_G24_B2, SystemTracker:umbksjdev:Queue:letsencrypt-input, Timestamp:4/30/2018 2:13:30 PM
   at Microsoft.ServiceBus.Messaging.Sbmp.DuplexRequestBindingElement.DuplexRequestSessionChannel.ThrowIfFaultMessage(Message wcfMessage)
   at Microsoft.ServiceBus.Messaging.Sbmp.DuplexRequestBindingElement.DuplexRequestSessionChannel.HandleMessageReceived(IAsyncResult result)
```

Kenneth

**Comment by mookid8000** [comment]
This usually happens when your handler takes too long to execute.

By default, Rebus will take peek locks on Azure Service Bus messages for the maximum allowed time, which is 5 minutes.

If your handler takes longer than that to finish its work, it will get `MessageLockLostException` when it tries to acknowledge (and thus delete) the message.

You should either a) take care to make handling of messages quicker, to be well within the 5 minute limit, or b) enable Rebus' automatic peek lock renewal (instructions can be found [here](https://github.com/rebus-org/Rebus/wiki/Azure-Service-Bus-transport#long-running-message-handlers)), which will make Rebus continually renew the peek locks when 80% of the time has elapsed.

Prefer (a) over (b) (because the peek lock renewal comes with a slight overhead), but sometimes that's not possible, and then (b) is ok 😉

**Comment by mookid8000** [comment]
Now I see it says `The message lock for message with ID 1e9682b3-e6ab-4c69-b702-88da2d957de4 was lost - tried to complete after 4,0 s` in your exception message – has the default peek locks interval been changed on the queue?

**Comment by KennethJakobsen** [comment]
@mookid8000 no I don't think so, but it was my first guess as well, but it's not:
![image](https://user-images.githubusercontent.com/17765492/39464610-cddd3bbe-4d1e-11e8-8b82-c12b63b5b955.png)

**Comment by mookid8000** [comment]
Damn, that's weird!

Azure Service Bus has had issues with stuff like this [in the past](https://stackoverflow.com/questions/14137160/azure-service-bus-peeklock-is-timing-out-after-just-five-seconds), but it should have been resolved a long time ago.

Can I see the relevant Rebus `Configure.With(...)` bits?

**Comment by KennethJakobsen** [comment]
```
  _bus = Configure.With(new LightInjectContainerAdapter(_container))
               .Transport(configurer => configurer.UseAzureServiceBus(_configurationSettings.ServiceBusConnectionString, Constants.Queues.LetsEncryptInput))
               .Routing(configurer =>
                {
                    configurer.TypeBased().MapAssemblyOf<AddNewHostnameCommand>(Constants.Queues.LetsEncryptInput);
                })
                .Options(configurer =>
                {
                    configurer.SetNumberOfWorkers(1);
                    configurer.SimpleRetryStrategy(secondLevelRetriesEnabled: false, maxDeliveryAttempts: 1);
                    configurer.SetMaxParallelism(1);
                })
                .Start();
```

**Comment by KennethJakobsen** [comment]
@mookid8000 Apparently that solved my issue, i'll keep testing. as this service need to be rock solid.

**Comment by mookid8000** [comment]
Oh well..... clearly a case of OMGWTFWHY?!?! 😫 but good to hear it solved your problem 🙂
