### ISSUE TITLE
Why are pre-fetching and retry features in client not used?

### ISSUE THREAD

**Issue by trevorreeves** [rebus-org/Rebus.AzureServiceBus#3]
The latest version of the Azure Service Bus client provides the following features, which are also implemented in the transport - was there a reason these have been implemented in the Transport and the client implementations not used?

- Pre-fetching
- Retries

**Comment by mookid8000** [comment]
As mentioned [here](https://github.com/rebus-org/Rebus.AzureServiceBus/issues/2#issuecomment-317239335) I once removed Rebus' own prefetching and replaced it by setting the PrefetchCount property on the input queue, but it didn't seem to improve the receive rate.

But as I also said, I might have done something wrong. Do you have any experience with this?

Regarding retries and error handling – Rebus uses its own error queues, mostly because this is the way it has always been. What do you think would be the benefit of using the native mechanism?

**Comment by trevorreeves** [comment]
Pre-fetching -> OK, fair enough.  I haven't focused on consumers yet in my load testing.
Retries -> Oh yeah, silly me! My Rebus lesson continues :-)

Thanks for the info.
