### ISSUE TITLE
Conflicting subscription names when using '/' in queue names

### ISSUE THREAD

**Issue by jmenziessmith** [rebus-org/Rebus.AzureServiceBus#5]
When creating queues, its possible to use / for structure. For example, I could have 2 queues : `notifications/command` and `payments/command`

Providing there are 2 services - a Notifications Service and a Payments Service, if both wish to subscribe to a particular topic, then the code will create a subscription called `command` for both cases. As a result, only one of the 2 services will receive the message.

This looks to be the culprit

https://github.com/rebus-org/Rebus.AzureServiceBus/commit/e37ff5fb172bacb01c3314ac996225719e69de20

Is there any reasoning for splitting the transport queue name on the '/' rather than just replacing it?

**Comment by mookid8000** [comment]
I didn't know that `/` was allowed in object names in Azure Service Bus.

It is pretty obvious that the Rebus code avoids passing `/` to the driver, reserving it for its own use as a "virtual" destination queue address to implement multicast.

It's hard for me, at this point, to tell whether opening up for using `/` in queue names and topics would be easy or hard. One thing I do know, though: This version of Rebus.AzureServiceBus is going to be completely rewritten some time later, because the `WindowsAzure.ServiceBus` is deprecated in favor of the new [`azure-service-bus-dotnet`](https://github.com/Azure/azure-service-bus-dotnet) driver (which is also supported on .NET Core)

**Comment by mookid8000** [comment]
For now, I suggest you avoid `/` in your queue names and use something else as a separator.

**Comment by Meyce** [comment]
The commit you highlighted was put in so that it would be possible to have virtual directories in ASB.  A couple of the ways I have used it is to organize queues and topics by environment(dev, staging, etc.), or to organize them by domain.

You may be able to  be able to decorate the ISubscriptionStorage interface so that you can fix up the path.

**Comment by jmenziessmith** [comment]
Thanks @mookid8000 . Its certainly possible to use / from what i can see. In service bus explorer, it uses them for structuring the queues into folders, which is pretty handy.

Is this what you are referring to @Meyce when you talk about virtual directories?

**Comment by Meyce** [comment]
@jmenziessmith, yes that is what I was referring to.  The screenshot below is using organization by environment.  It allows us to organize topics by environment and get more use out of a single ASB namespace, and not have to worry about collisions due to names being the same.

![image](https://user-images.githubusercontent.com/9484306/30459918-8fcb6220-9981-11e7-85df-be753fe7efc6.png)

**Comment by mookid8000** [comment]
Sorry for my misunderstanding here! 😶 I think I understand the issue now 😁

**Comment by mookid8000** [comment]
Wow is this still open – I think this was fixed a long time ago, and I just ensured that it works fine with the new transport also.
