### ISSUE TITLE
Autodelete for subscriptions?

### ISSUE THREAD

**Issue by ktjn** [rebus-org/Rebus.AzureServiceBus#80]
ASB supports autodelete for subscriptions. Rebus supports this for queues. Is there a way to enable autodeletes for subscriptions as well?

I can even implement this if I get some hints on how to do it.

**Comment by mookid8000** [comment]
How would you expect it to work?

Would you expect the subscription to disappear if the subscriber had not consumed anything from it for a while?

Or would you expect the subscription to disappear if there had not been published anything to its topic for a while?

**Comment by ktjn** [comment]
Was thinking about this: https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.subscriptiondescription.autodeleteonidle?view=azure-dotnet

Current workaround is updating this after the subscriptions are setup by rebus.

 ```csharp
                      var serviceBusConnectionStringProperties = ServiceBusConnectionStringProperties.Parse(GetAzureServiceBusConfiguration(configuration, environment));
                      var client = new ServiceBusAdministrationClient(serviceBusConnectionStringProperties.FullyQualifiedNamespace, new DefaultAzureCredential());
                      foreach (var topic in topics)
                      {
                          var subscriptions = client.GetSubscriptionsAsync(topic);
                          await foreach (var subscription in subscriptions)
                          {
                              if (subscription.SubscriptionName == inputQueueName)
                              {
                                  subscription.AutoDeleteOnIdle = TimeSpan.FromMinutes(5);
                                  await client.UpdateSubscriptionAsync(subscription);
                              }
                          }
                      }
```

**Comment by mookid8000** [comment]
Oh, so you have something that actually works right now?

I've discussed this particular feature with someone recently, and somehow we got the impression that auto-delete on subscriptions would not make sense, because they would be considered idle only when they had not received any events for a while, which is definitely NOT what you want.

Rebus uses subscriptions by configuring them to forward messages to the input queue of the consumer - how does that work together with auto-delete on the queue combined with auto-delete on the subscriptions?

**Comment by ktjn** [comment]
Hmm... I might have got it wrong. The problem is that we use auto delete on idle for queues, which works fine for dynamic queues. But the subscriptions are left even if the queue is removed.

The logical way would be to set auto delete on the subscriptions itself so it is removed when the queue is gone. 

I'll do some research regarding this autodelete on subscription.

**Comment by mookid8000** [comment]
I just made a few experiments with ASB, and it turned out, unfortunately, that auto-delete-on-idle cannot be combined with forwarding on subscriptions. When the `ForwardTo` property is set on the subscription, the `AutoDeleteOnIdle` timeout is simply ignored and set to `TimeSpan.MaxValue`.

The test is here: https://github.com/rebus-org/Rebus.AzureServiceBus/blob/master/Rebus.AzureServiceBus.Tests/Checks/CheckWhatHappensWhenSubscriptionHasAutodeleteOnIdleSet.cs#L23

**Comment by ktjn** [comment]
Hehe. Just came to that conclusion myself. 

I think I will just clean subscriptions with no valid queue during startup. Auto delete on queues works just fine.

Thanks for the info.

**Comment by ktjn** [comment]
For anyone having the same problem:

This check if the queue is still active. If not the subscription is removed.

```csharp
foreach (var topic in topics) 
{
    var subscriptions = client.GetSubscriptionsAsync(topic);
    await foreach (var subscription in subscriptions)
    {
        if (subscription.SubscriptionName.StartsWith(queuePrefix))
        {
            try
            {
                await client.GetQueueAsync(subscription.SubscriptionName);
                log.LogInformation("Subscription {Name} still active", subscription.SubscriptionName);
            }
            catch (ServiceBusException e) when (e.Reason ==
                                                ServiceBusFailureReason.MessagingEntityNotFound)
            {
                log.LogInformation("Found stale subscription {Name}, deleting...", subscription.SubscriptionName);
                try
                {
                    await client.DeleteSubscriptionAsync(topic, subscription.SubscriptionName);
                }
                catch (Exception ex)
                {
                    log.LogWarning(ex, "Failed to delete subscription, ignoring...");
                }
            }
        }
        log.LogInformation("Subscription {Name} not matching prefix", subscription.SubscriptionName);
    }
}
```
